name: Update Code Stats
permissions:
  contents: write

on:
  push:
    branches: [ master ]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install cloc
        run: sudo apt install cloc

      - name: Generate stats
        run: |
          cloc --md --out=stats.md .
          cat stats.md

      - name: Commit stats
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          mv stats.md README_STATS.md
          git add README_STATS.md
          git commit -m "Update stats" || echo "No changes"
          git push
